---
title: "R Notebook"
output: html_notebook
---


```{r}
#install.packages(c("rstanarm", "BayesTree", "ggplot2", "forcats"))
library(rstanarm)
library(BayesTree)
library(ggplot2)
library(forcats)
bart_sim <- read.csv('bart_sim.csv')
head(bart_sim)
```

```{r}
Treated <- bart_sim[bart_sim['Z']==1,]
Control <- bart_sim[bart_sim['Z']==0,]
SMD1 <- abs(mean(Treated$X1) - mean(Control$X1)) / sd(Treated$X1)
SMD1
```

```{r}
Treated <- bart_sim[bart_sim['Z']==1,]
Control <- bart_sim[bart_sim['Z']==0,]
SMD1 <- abs(mean(Treated$X1) - mean(Control$X1)) / sd(Treated$X1)
SMD1
```

```{r}
lm1 <- glm(Z ~ X1 + X2 + X1:X2, family = binomial(link="logit"), data=bart_sim)
bart_sim$p_estimate <- invlogit(predict(lm1))
control_min = min(bart_sim[bart_sim$Z==0,"p_estimate"])
control_max = max(bart_sim[bart_sim$Z==0,"p_estimate"])
data_trim <- bart_sim[(bart_sim$p_estimate<=control_max) & (bart_sim$p_estimate>=control_min),]
Treated2 <- data_trim[data_trim['Z']==1,]
Control2 <- data_trim[data_trim['Z']==0,]
SMD2 <- abs(mean(Treated2$X2) - mean(Control2$X2)) / sd(Treated2$X2)
SMD2
```

```{r}
keep_cols = c('X1','X2','Z','p_pred','p')
xt <- data_trim[keep_cols]
xp <- data_trim[data_trim$Z==1,keep_cols]
xp$Z = 0
y <- data_trim$Y
bart.trim <- bart(x.train=xt, y.train=y, x.test=xp)
diffs = bart.trim$yhat.train[,data_trim$Z==1] - bart.trim$yhat.test 
mndiffs=apply(diffs,1,mean)
ATT_bart = mean(mndiffs) # Posterior mean SATE
sdATT_bart = sd(mndiffs) # Posterior standard deviation of the SATE
ATT_bart
sdATT_bart
```

```{r}
covariates <- c('X1','X2')
ite_means<- apply(diffs, 2, mean)
ite_sds<- apply(diffs, 2, sd)
ite_ql = apply(diffs, 2, quantile, .025)
ite_qu = apply(diffs, 2, quantile, .975)
for (cov in covariates){
  covplot = data_trim[, cov]
  plot(covplot[data_trim$Z==1], ite_means, pch=16, cex=0.75, col="red", ylim = c(-1,5), 
       main = paste("ITEs as a funciton of:", cov), xlab = cov, ylab = "ITE")
  arrows(covplot[data_trim$Z==1], ite_ql, covplot[data_trim$Z==1], ite_qu, col = rgb(0.5,0,0, alpha=0.5), angle=90, length=0.025, lwd=0.5)
}

fit_bart <- function(data){
  keep_cols = c('X1','X2','Z','p_pred','p')
  xt <- data[keep_cols]
  xp <- data[data$Z==1,keep_cols]
  xp$Z = 0
  y <- as.numeric(data$Y)
  data$Z <- as.numeric(data$Z)
  bart.model <- bart(x.train=xt, y.train=y, x.test=xp)
  diffs <- bart.model$yhat.train[,data$Z==1] - bart.model$yhat.test
  mndiffs <- apply(diffs,1,mean)
  return (mndiffs)
}

column <- data_trim$X2
t1 <- quantile(column, 1/3)[[1]]
t2 <- quantile(column, 2/3)[[1]]
data_t1 <- data_trim[column <= t1,]
data_t2 <- data_trim[(t1 < column) & (column <= t2),]
data_t3 <- data_trim[column > t2,]

mn_diff_t1 <- fit_bart(data_t1)
mn_diff_t2 <- fit_bart(data_t2)
mn_diff_t3 <- fit_bart(data_t3)

hm <- mn_diff_t3 - mn_diff_t2
lm <- mn_diff_t1 - mn_diff_t2
l <- length(mn_diff_t2)
results_df <- data.frame(diffs=c(hm,lm), comparison=c(rep('high',l),rep('low',l)) )

ggplot(data=results_df, aes(x=fct_rev(comparison), y=diffs, fill=comparison)) +
  geom_violin() +
  geom_boxplot() +
  ggtitle("ATT Comparison to Medium X2")

```

```{r}
reg_mod <- stan_glm(Y ~ Z + X1 + X2 + X1:X2 + Z:X1, data=data_trim)
ATE_reg = reg_mod$coefficients["Z"]
sdATE_reg = reg_mod$ses["Z"]
ATE_reg
sdATE_reg
```

```{r}
preddat = data_trim
preddat$Z=0
ypred2 = posterior_predict(reg_mod, newdata=preddat)
ATTmat = data_trim$Y[data_trim$Z==1] - ypred2[data_trim$Z==1]
ATT_2 = mean(rowMeans(ATTmat))
sdATT_2 = sd(rowMeans(ATTmat))
ATT_2
sdATT_2
```

```{r}
ans <- ATT_2 - ATT_bart
ans
```
